### ISSUE TITLE
Add a place and something interesting about you.

### ISSUE THREAD

**Issue by swarajlaha** [swarajlaha/hactoberexplor#4]
If this is your first pull request, please read this article: [How To Create a Pull Request on GitHub](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github)

### Step 1

Fork the repo by pressing the "Fork" button on the top right side of the
repository and clone your forked repository.

### Step 2

In your forked repository, edit "index.html" and add your place's picture, place's name and a short dscription about it. Also add something interesting about yourself and a picture of yours. Please read the simple instructions (comments) carefully, while editing the html file.

1. In _index.html_, start copying from the line with _div class="col-1-of-3"_ till the end of the div (also        marked in the file), in order to add content in it.
2. Go to _img/places/_ folder and add your Place Pic in the naming format, _place[no.].jpg_, like, _place1.jpg_,    _place2.jpg_ and so on and mention the path, in the _img_ tag.
3. Add the Name of your Place, in place of _Place Demo_, inside the _span tag_.
4. Add a short description about your place, in place of the random text, inside the _p tag_.
5. For the _About Contributors_ section, add an image of yours in _img/contributors/_ folder, in the naming            format, _contributor[no.].jpg_, like _contributor1.jpg_, _contributor2.jpg_ and so on and mention the path, in the _img_ tag, like you did for the places.
6. In the _figcaption tag_, mention your name.
7. In the _h3 tag_, give a tile about yourself.
8. In the _p tag_, write something interesting about yourself, alongwith some social media links, for people to      find you.
         **That's it!** 

### Step 3 

Commit your changes and submit a pull request! After your pull request gets accepted, you will be able to see your very own profile on the [HacktoberExplor](https://swarajlaha.github.io/hactoberexplor/) !!

### Step 4

Please star the repo, if you like this fun little Hacktoberfest project :heart:

**Comment by shathurshan** [comment]
I am interested
